### ISSUE TITLE
Error in Loading GLX

### ISSUE THREAD

**Issue by safeeulbashir** [BCLab-UNM/iAnt-ARGoS#3]
Tried to run the code in CS machine. Used previous version of qtuser function. While running argos, it is not showing the visualization of the field. I have searched in the internet for similar errors.Probably its some kind of driver issue. But I think it can be resolved from the code. Please have a look.  

![error](https://cloud.githubusercontent.com/assets/6511438/7094047/85be8126-df7b-11e4-8928-94ae64e027a1.png)

**Comment by Antonio-Griego** [comment]
In order to help figure out exactly what is going on, I'd like to ask a few questions:
- Do you get any errors when you compile the code using the previous version of the qt user functions?
- If possible, could you please link to me copies of the iAnt_qt_user_functions .h and .cpp files?
- Try deleting everything within the BUILD folder in the iAnt-ARGoS folder and running the compilation from the beginning (sometimes this can help to fix errors where code isn't being recompiled correctly)

Other possible sources of problems that may be out of your control could include the fact that certain packages may be out of date and/or updated to versions too new for ARGoS to use. xlib / GLX is a suspect in this case because all of those warnings should never display when ARGoS is running properly.

--Antonio

**Comment by safeeulbashir** [comment]
When I try to run, I always remove the earlier files and then I do cmake command. After that I do make. Well the thing is that the problem is in some CS Machines. Not in all machines. Cause I have instructed the student who is getting this error to use some other computer. And he succeeded to run it. I think there are some conflict with the library(Most likely with the NVDIA)
However, Its not possible to add the source files here. I will email those to you.
